# overall
title: wkylin resume

# page 1
name: wkylin
nickname: wkylin
introduce: Front End Manager
social:
  github: //github.com/wkylin 
  wechat: assets/wechat.jpg
  email: wkylin.w@gmail.com
  juejin: //juejin.im/user/5794851c128fe10056b62644
  tele: 15026835870
pdf_name: '[WKYLIN_RESUME.pdf](assets/resume.pdf)'

# page 2
education:
  title: 教育背景
  stages:
    - 
      time: 2003.06 - 2017.12 
      university: 西安电子科技大学
      major: 计算机信息管理
    
# page 3
work_experience:
  title: 工作经历
  stages: 
    - 
      company: 资邦金服网络科技集团有限公司
      job_title: Front End Manager
      time: 2017.3 - 至今
      tech_stack:
        - Vue
        - Webpack
        - TypeScript
      description:
        - H5前端开发...
        - 唐小僧是资邦金服旗下移动金融生活服务平台。
    - 
      company: 江苏大泰信息技术有限公司上海分公司
      job_title: Senior Front End Developer 
      time: 2015.6 - 2017.3
      tech_stack:
        - Angular
        - Webpack
      description:
        - 维护前端组件，改进前端框架...
        - 识基：让你更懂基金，中国证监会核准的基金销售机构，一站式专业基金销售服务平台

# page 4
open_source:
  title: 开源作品
  works:
    - 
      name: Angular Funs
      abstract: Angular funs...
      link: https://wkylin.github.io/ng-funs/#/home
      tech_stack: angular scss angular-cli pwa
      description: 
        - Angular funs. 
    - 
      name: Angular Next
      abstract: Angular Next...
      link: https://github.com/wkylin/ng-next
      tech_stack: angular scss angular-cli pwa
      description: 
        - Angular funs. 
    - 
      name: Github Page
      abstract: GitHub Page...
      link: http://wkylin.github.io/
      tech_stack: jekyll bootstrap jquery
      description: 
        - Wkylin GitHub Page. 
    
# page 5
tech_stack:
  title: 专业技能
  techs:
    - HTML5
    - CSS3
    - ES5/6/7
    - Webpack
    - VUE
    - Angular
    - Ionic
    - Node/Express
    - TypeScript
    - PWA
    - SSR
    - SEO
    - Git
    - jQuery
    - Grunt
    - Gulp
    - Front End Engineering
    - Performance Optimization 
